spring.application.name=learn-vault
spring.datasource.url=jdbc:postgresql://localhost:5432/learnvault
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
server.port=8001
jwt.secret = 2tTNCo6t7U7TuHA0pvsHkzToD4Eabq/iV/3mNpqHs1M=
