spring:
  application:
    name: learn-vault
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/learnvault}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:yourpassword}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}
            scope: email, profile
            redirect-uri: ${OAUTH2_CLIENT_REDIRECT_URI:https://learn-vault-six.vercel.app/login/oauth2/code/google}

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET:2tTNCo6t7U7TuHA0pvsHkzToD4Eabq/iV/3mNpqHs1M=}

app:
  oauth2-redirect: ${OAUTH2_REDIRECT_URL:http://localhost:5173/dashboard}
  cookie-secure: ${COOKIE_SECURE:false}
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,https://learn-vault-six.vercel.app,https://learn-vault-*.vercel.app}

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:dummy}
    secret: ${RAZORPAY_SECRET_ID:dummy}


aws:
  access:
    key: ${AWS_ACCESS_KEY:}
  secret:
    key: ${AWS_SECRET_KEY:}
  region: ${AWS_REGION:ap-south-1}
  s3:
    bucketName: ${AWS_BUCKETNAME:}

management: 
  endpoints:
    web: 
      exposure:
        include: health