spring:
  application:
    name: learn-vault
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/learn-vault}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}
            scope: email, profile

server:
  port: ${SERVER_PORT:8001}

jwt:
  secret: ${JWT_SECRET:2tTNCo6t7U7TuHA0pvsHkzToD4Eabq/iV/3mNpqHs1M=}

app:
  oauth2-redirect: ${OAUTH2_REDIRECT_URL:http://localhost:5173/dashboard}
  cookie-secure: ${COOKIE_SECURE:false}

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:dummy}
    secret: ${RAZORPAY_SECRET_ID:dummy}


aws:
  access:
    key: ${AWS_ACCESS_KEY:}
  secret:
    key: ${AWS_SECRET_KEY:}
  region: ${AWS_REGION:ap-south-1}
  s3:
    bucketName: ${AWS_BUCKETNAME:}
